name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the workflow on version tags

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies and ldd
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libc-bin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile website-existence-checker.py
        env:
          PATH: /opt/hostedtoolcache/Python/3.x.x/x64/bin:$PATH

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: website-existence-checker-${{ matrix.os }}
          path: dist/website-existence-checker*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download executables
        uses: actions/download-artifact@v2
        with:
          name: website-existence-checker-ubuntu-latest
          path: website-existence-checker-ubuntu-latest

      - name: Download executables
        uses: actions/download-artifact@v2
        with:
          name: website-existence-checker-macos-latest
          path: website-existence-checker-macos-latest

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: website-existence-checker-ubuntu-latest/website-existence-checker
          asset_name: website-existence-checker-ubuntu
          asset_content_type: application/octet-stream

      - name: Upload Release Asset MacOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: website-existence-checker-macos-latest/website-existence-checker
          asset_name: website-existence-checker-macos
          asset_content_type: application/octet-stream
